package com.motorro.sqlite.db

import android.content.Context
import android.net.Uri
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.room.TypeConverters
import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase
import com.motorro.sqlite.data.Converters
import com.motorro.sqlite.data.Image
import com.motorro.sqlite.data.ListImage
import com.motorro.sqlite.data.PhotoFilter
import kotlinx.coroutines.flow.Flow

/**
 * Wrapper for Room database
 * Uses Room DAO to access data
 * @param db Room database
 */
class PhotoDbImpl private constructor(private val db: RoomDb): PhotoDb {
    override fun getList(filter: PhotoFilter): Flow<List<ListImage>> = when {
        filter.isEmpty -> db.imageDao().getList()
        else -> db.imageDao().getList("${filter.name.orEmpty()}%")
    }

    override suspend fun addImage(image: Image) {
        db.imageDao().insert(image)
    }

    override suspend fun deleteImage(imagePath: Uri) {
        db.imageDao().deleteImage(imagePath.toString())
    }

    companion object {
        private const val DATABASE_NAME = "photo.db"

        fun create(context: Context): PhotoDb = PhotoDbImpl(
            Room
                .databaseBuilder(context, RoomDb::class.java, DATABASE_NAME)
                .addMigrations(MIGRATION_1_2)
                .build()
        )
    }
}

/**
 * Photo database implementation generated by Room
 */
@Database(
    entities = [Image::class],
    version = 2,
    exportSchema = true
)
@TypeConverters(Converters::class)
internal abstract class RoomDb : RoomDatabase() {

    abstract fun imageDao(): PhotoDao

}

/**
 * Migration from version 1 (Vanilla) to 2 (Room)
 */
val MIGRATION_1_2 = object : Migration(1, 2) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_photo_name` ON `photo` (`name`)")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_photo_created` ON `photo` (`created`)")
    }
}