package com.motorro.cookbook.app.db

import android.content.Context
import androidx.room.AutoMigration
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.room.TypeConverters
import com.motorro.cookbook.app.db.entity.Converters
import com.motorro.cookbook.app.db.entity.ListRecipeEntity
import com.motorro.cookbook.app.db.entity.RecipeDataEntity

/**
 * Recipes database implementation generated by Room
 */
@Database(
    entities = [
        ListRecipeEntity::class,
        RecipeDataEntity::class
    ],
    version = 2,
    exportSchema = true,
    autoMigrations = [
        AutoMigration(1, 2)
    ]
)
@TypeConverters(Converters::class)
abstract class CookbookDb : RoomDatabase() {

    abstract fun recipesDao(): CookbookDao

    companion object {
        /**
         * Creates a new instance of the database
         * @param context Application context
         */
        fun create(context: Context): CookbookDb {
            return Room.databaseBuilder(
                context,
                CookbookDb::class.java,
                "recipes.db"
            ).build()
        }
    }
}
