@startuml
'https://plantuml.com/state-diagram

[*] -> Content

Content -> AuthPrompt
Content -> LoggingOut
Content --> Finished

Finished -> [*]

state Auth {
    state AuthPrompt

    AuthPrompt --> LoginForm
    AuthPrompt --> RegisterForm

    state Login {
      state LoginForm
      LoginForm -> LoggingIn
      LoggingIn -> LoginError
      LoginError -left-> LoggingIn
    }

    state Register {
      state RegisterForm
      RegisterForm -> Registering
      Registering -> RegisterError
      RegisterError -left-> Registering
    }
}

Auth --> Content
LoggingOut --> Content

@enduml