@startuml
'https://plantuml.com/class-diagram

hide empty members

interface ActivityResultContract<I, O> {
    + createIntent(context: Context, input: I): Intent
    + parseResult(resultCode: Int, data: Intent?): O?
}

interface ActivityResultCallback<O> {
    + onResult(result: O)
}

interface ActivityResultLauncher<I> {
    + launch(input: I)
}


@enduml